import {catalog,eras,rules,units,builds} from '../content/catalog';
import {loadoutFor,type Profile} from '../core/profile';
import type {MatchConfig} from '../core/types';
import type {Battle} from '../core/battle';
import {assetPath} from '../presentation/assets';
import {ageSpecials} from '../core/age-specials';
import {activeItems,activeItemIds} from '../core/active-items';
import {uiIcon} from './icons';

export const escapeHtml=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const art=(key:string,label:string,decorative=false)=>assetPath(key) ? `<img src="${assetPath(key)}" alt="${decorative ? '' : escapeHtml(label)}" draggable="false">` : '';
const eraIcons=['stone','bronze','crown','factory','orbit'];
const specialIcons=['meteor','flame','arrows','plane','beam'];
const modeInfo={
  campaign:{title:'续火盟战役',description:'十五场战役，逐步学会阵线与换代。'},
  standard:{title:'五时代文明对战',description:'盾兵稳住前线，火力叠在后方。下一次进化，由你决定。'},
  challenge:{title:'王国攻防',description:'固定军令，迎战工业防线。'},
  trial:{title:'战术演练',description:'练习出兵、进化与技能，不发放奖励。'},
};
export function menuMarkup(profile:Profile,selectedHero:string,mode:MatchConfig['mode'],difficulty:string,saved:boolean,ready:boolean,heroEnabled=false){
  const hero=catalog.heroes[selectedHero],loadout=mode==='challenge' ? builds.find(b=>b.heroId===selectedHero)! : loadoutFor(profile,selectedHero),info=modeInfo[mode];
  return `<div class="home-screen rounded-home"><header class="home-top"><a class="brand-mark" href="#" data-action="menu">${uiIcon('flag')}<span>续火盟</span></a><div class="profile-summary"><span title="战役进度">${uiIcon('map')}<b>${profile.clearedMissionIds.length}<small>/15</small></b></span><span title="遗物收藏">${uiIcon('relic')}<b>${profile.ownedRelicIds.length}<small>/12</small></b></span></div><button class="icon-button" data-action="settings" aria-label="设置与档案">${uiIcon('gear')}</button></header>
    <div class="home-main"><section class="home-copy"><span class="eyebrow">从第一簇火，到最后一颗星</span><h1>一线万年<span>文明冲锋</span></h1><div class="era-journey" aria-label="五个时代">${eras.map((e,i)=>`<span title="${e.name}">${uiIcon(eraIcons[i])}<small>${e.name}</small></span>`).join('')}</div>
      <nav class="mode-options" aria-label="游戏模式">${[['standard','对战','sword'],['campaign','战役','map'],['challenge','挑战','shield'],['trial','演练','target']].map(([id,name,glyph])=>`<button data-action="mode" data-value="${id}" aria-pressed="${mode===id}">${uiIcon(glyph)}${name}</button>`).join('')}</nav><div class="mode-description"><strong>${info.title}</strong><p>${info.description}</p></div><div class="difficulty" aria-label="难度">${rules.difficulty.map(d=>`<button data-action="difficulty" data-value="${d.id}" aria-pressed="${difficulty===d.id}">${d.name}</button>`).join('')}</div><div class="menu-actions"><button class="primary start-button" data-action="start" ${ready ? '' : 'disabled'}>${uiIcon('play')}${mode==='campaign' ? '进入战役' : '开战'}${uiIcon('arrow')}</button>${saved ? `<button class="resume-button" data-action="resumeSaved" ${ready ? '' : 'disabled'}>${uiIcon('play')}继续上次</button>` : ''}</div><p class="home-caption" id="loading-message">${ready ? '一场对战 · 五次文明登场' : '正在集结军团…'}</p></section>
    <div class="commander-art" aria-hidden="true"><div class="commander-halo"></div>${art(`hero.${hero.id}`,hero.name,true)}<span class="commander-name">${hero.name}<small>${hero.title}</small></span></div>
    <aside class="commander-select"><button class="hero-extension" data-action="heroToggle" aria-pressed="${heroEnabled}">${uiIcon('flag')}<span><strong>指挥官扩展</strong><small>${heroEnabled ? '英雄与三项军令参战' : '开启后加入英雄与军令'}</small></span><i class="switch ${heroEnabled ? 'on' : ''}"></i></button>${heroEnabled ? `<div class="hero-options">${profile.unlockedHeroIds.map(id=>{const h=catalog.heroes[id];return `<button class="hero-choice" data-action="hero" data-value="${id}" aria-pressed="${selectedHero===id}" aria-label="选择${h.name}">${art(`portrait.${id}`,h.name,true)}<span><strong>${h.name}</strong><em>${h.title}</em></span>${selectedHero===id ? uiIcon('check') : ''}</button>`;}).join('')}</div><div class="loadout-preview">${[hero.signatureSkillId,...loadout.commonSkillIds].map(id=>`<span title="${catalog.skills[id].name}">${art(`skill.${id}`,catalog.skills[id].name,true)}</span>`).join('')}</div><button class="council-link" data-action="loadout">${uiIcon('sword')}调整军令${uiIcon('arrow')}</button>` : `<div class="classic-preview">${['U11','U12','U34','U54'].map(id=>art(`icon.${id}`,catalog.units[id].name,true)).join('')}<span>出兵 · 强化 · 进化</span></div>`}</aside></div>
    <nav class="camp-navigation" aria-label="营地导航">${[['loadout','sword','军议'],['collection','relic','收藏'],['encyclopedia','book','图鉴'],['settings','gear','设置']].map(([action,key,title])=>`<button data-action="${action}">${uiIcon(key)}<span><strong>${title}</strong></span></button>`).join('')}</nav></div>`;
}
export function battleHud(battle:Battle){
  const player=battle.state.sides[0],hero=catalog.heroes[player.loadout.heroId],cards=units.filter(u=>u.eraId===player.eraId),skillIds=[hero.signatureSkillId,...player.loadout.commonSkillIds],eraIndex=eras.findIndex(e=>e.id===player.eraId),special=ageSpecials[player.eraId as keyof typeof ageSpecials],withHero=battle.state.config.heroEnabled!==false;
  return `<header class="war-top compact-top"><button class="base-pill ally" data-action="camera" data-value="ally" aria-label="定位己方基地"><span class="base-emblem">${uiIcon(eraIcons[eraIndex])}</span><div><b data-text="allyEra"></b><progress id="ally-hp" aria-label="己方基地生命"></progress><small data-text="allyHp"></small></div></button><div class="resource-pills"><span class="gold-pill" title="金币：训练、强化与炮塔">${uiIcon('coin')}<b data-text="gold"></b></span><span class="xp-pill" title="战斗经验：进化与时代大招">${uiIcon('spark')}<b data-text="knowledge"></b><small>XP</small></span><span class="command-pill" title="军令：英雄技能与主动道具">${uiIcon('crown')}<b data-text="command"></b></span></div><div class="battle-time"><time class="battle-clock" data-text="time"></time><small data-text="wave"></small></div><button class="base-pill enemy" data-action="camera" data-value="enemy" aria-label="定位敌方基地"><div><b data-text="enemyEra"></b><progress id="enemy-hp" aria-label="敌方基地生命"></progress><small data-text="enemyHp"></small></div>${uiIcon('shield')}</button><button class="icon-button pause-button" data-action="pause" aria-label="暂停">${uiIcon('pause')}</button></header>
    <div class="viewport-controls"><button class="icon-button" data-action="mapToggle" aria-label="展开或收起小地图" aria-expanded="false">${uiIcon('map')}</button><button class="icon-button camera-follow" data-action="camera" data-value="front" id="follow-front" aria-label="跟随前线">${uiIcon('flag')}</button><button class="icon-button" data-action="trainingMenu" aria-label="管理训练队列">${uiIcon('people')}</button><button class="icon-button" data-action="unitHelp" aria-label="查看当前兵种说明">${uiIcon('info')}</button><div class="map-controls" hidden><button data-action="camera" data-value="left" aria-label="战场向左移动">${uiIcon('back')}</button><div class="minimap" id="battle-minimap" role="slider" tabindex="0" aria-label="战场视野位置" aria-valuemin="0" aria-valuemax="600" aria-valuenow="0"><i class="map-line"></i><span class="map-base ally"></span><span class="map-base enemy"></span><span id="map-fighters"></span><i id="map-window"></i></div><button data-action="camera" data-value="right" aria-label="战场向右移动">${uiIcon('arrow')}</button></div></div>
    <div class="aim-instruction" id="aim-instruction" hidden><span id="aim-description"></span><button data-action="cancelAim" aria-label="取消瞄准">${uiIcon('back')}</button></div><div class="battle-hint" id="battle-hint" hidden></div>
    <footer class="war-dock compact-bottom"><div class="recruitment"><div class="recruit-cards">${cards.map((u,i)=>{const specialLabel=typeof u.special.auraLabel==='string' ? u.special.auraLabel : u.special.firstContactBonus ? '猎袭：奔袭后的首次命中更重' : '';return `<button class="recruit-card ${specialLabel ? 'special-unit' : ''} ${u.heavy && !battle.heavyUnlocked(0) ? 'locked' : ''}" data-action="${u.heavy && !battle.heavyUnlocked(0) ? 'researchMenu' : 'train'}" data-value="${u.id}" id="unit-${u.id}" aria-label="${u.name}，${battle.unitCost(0,u.id)}金币" title="${u.name} · ${u.range}射程 · ${u.heavy ? '重型克制步兵，攻城伤害×2.6' : u.role==='front' ? '步兵克制支援' : u.role==='ranged' ? '支援克制反装甲' : '反装甲克制重型'}${specialLabel ? ` · ${specialLabel}` : ''}">${art(`icon.${u.id}`,u.name,true)}<span class="unit-price">${uiIcon(u.heavy && !battle.heavyUnlocked(0) ? 'lock' : 'coin')}<b>${battle.unitCost(0,u.id)}</b></span><kbd>${i+1}</kbd>${specialLabel ? '<i class="special-badge">✦</i>' : ''}</button>`;}).join('')}</div><div class="queue-row"><span class="population" title="在场单位">${uiIcon('people')}<small data-text="population"></small></span><div class="queue" id="training-queue"></div></div></div>
    <div class="active-items" aria-label="主动道具">${activeItemIds.map(id=>{const item=activeItems[id];return `<button class="item-orb" data-action="item" data-value="${id}" id="item-${id}" aria-label="${item.name}" title="${item.name} · ${item.description}">${uiIcon(item.icon)}<b id="item-count-${id}">${item.charges}</b><small id="item-state-${id}">${item.shortName}</small><i class="item-cooldown" id="item-cooldown-${id}"></i></button>`;}).join('')}</div>
    <div class="era-controls"><button class="round-command research-button" data-action="researchMenu" id="research" aria-label="金币强化" title="金币强化">${uiIcon('sword')}</button><button class="round-command fort-orb" data-action="fort" id="fort" aria-label="基地炮塔" title="基地炮塔">${uiIcon('tower')}<small data-text="turretCount"></small></button><button class="round-command special-button" data-action="ageSpecial" id="age-special" aria-label="${special.name}，消耗${special.cost}战斗经验" title="${special.name} · ${special.cost} XP">${uiIcon(specialIcons[eraIndex])}<small id="age-special-state">${special.cost}</small></button><button class="round-command evolve-orb" data-action="evolve" id="evolve" aria-label="进入下一个时代" title="时代进化"><i id="evolve-progress"></i><span class="era-glyph">${uiIcon(eraIcons[Math.min(4,eraIndex+1)])}</span><strong data-text="evolveCost"></strong></button></div>
    ${withHero ? `<div class="commander"><button class="hero-orb" data-action="heroOrders" id="hero-orb" aria-label="展开或收起英雄军令" aria-expanded="false">${art(`portrait.${hero.id}`,hero.name,true)}<small data-text="command"></small><progress id="hero-hp" aria-label="指挥官生命"></progress></button><div class="hero-orders" hidden><div class="stances" id="stance-options">${[['cover','掩护','shield'],['rush','冲锋','sword'],['retreat','撤回','back']].map(([stance,label,glyph])=>`<button data-action="stance" data-value="${stance}" id="stance-${stance}" aria-label="${label}" title="${label}">${uiIcon(glyph)}</button>`).join('')}</div><div class="skill-cards">${skillIds.map((id,i)=>`<button class="skill-card" data-action="skill" data-value="${i}" id="skill-${id}" aria-label="${catalog.skills[id].name}" title="${escapeHtml(catalog.skills[id].description)}">${art(`skill.${id}`,catalog.skills[id].name,true)}<small id="skill-state-${id}"></small><span class="cooldown-mask" id="cooldown-${id}"></span><kbd>${['Q','W','E'][i]}</kbd></button>`).join('')}</div><span class="commander-meter" data-text="heroStatus"></span></div></div>` : ''}</footer>`;
}
