import rawEras from '../../docs/epoch-rush/data/eras.json';
import rawHeroes from '../../docs/epoch-rush/data/heroes.json';
import rawUnits from '../../docs/epoch-rush/data/units.json';
import rawSkills from '../../docs/epoch-rush/data/skills.json';
import rawSpecs from '../../docs/epoch-rush/data/specializations.json';
import rawTalents from '../../docs/epoch-rush/data/talents.json';
import rawRelics from '../../docs/epoch-rush/data/relics.json';
import rawUpgrades from '../../docs/epoch-rush/data/run-upgrades.json';
import rawTurrets from '../../docs/epoch-rush/data/turrets.json';
import rawWeapons from '../../docs/epoch-rush/data/weapons.json';
import rawMissions from '../../docs/epoch-rush/data/missions.json';
import rawBuilds from '../../docs/epoch-rush/data/builds.json';
import rawEnemies from '../../docs/epoch-rush/data/enemy-profiles.json';
import rules from '../../docs/epoch-rush/data/rules.json';
import loot from '../../docs/epoch-rush/data/loot.json';
import type { Era, Hero, Unit, Skill, Specialization, Talent, Relic, Upgrade, Turret, Weapon, Mission, Build, EnemyProfile, Named } from '../core/types';

const index = <T extends Named>(rows: T[]) => Object.fromEntries(rows.map(row => [row.id, row])) as Record<string, T>;
export const eras = rawEras as unknown as Era[];
export const heroes = rawHeroes as Hero[];
export const units = rawUnits as unknown as Unit[];
export const skills = rawSkills as unknown as Skill[];
export const specializations = rawSpecs as Specialization[];
export const talents = rawTalents as Talent[];
export const relics = rawRelics as Relic[];
export const upgrades = rawUpgrades as Upgrade[];
export const turrets = rawTurrets as Turret[];
export const weapons = rawWeapons as Weapon[];
export const missions = rawMissions as Mission[];
export const builds = rawBuilds as Build[];
export const enemies = rawEnemies as EnemyProfile[];
export const catalog = { eras: index(eras), heroes: index(heroes), units: index(units), skills: index(skills), specializations: index(specializations), talents: index(talents), relics: index(relics), upgrades: index(upgrades), turrets: index(turrets), weapons: index(weapons), missions: index(missions), builds: index(builds), enemies: index(enemies) };
export { rules, loot };
